<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>N3O.Umbraco.NestedContentMigration.Cli</RootNamespace>
        <AssemblyName>nc-migrate</AssemblyName>
        <LangVersion>12</LangVersion>
        <Nullable>disable</Nullable>
        <ImplicitUsings>disable</ImplicitUsings>
        <InvariantGlobalization>false</InvariantGlobalization>
        <IsPackable>false</IsPackable>
    </PropertyGroup>
    <PropertyGroup Condition="'$(StandaloneExe)' == 'true'">
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <SelfContained>true</SelfContained>
        <PublishSingleFile>true</PublishSingleFile>
        <PublishTrimmed>false</PublishTrimmed>
        <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
        <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="HtmlAgilityPack" Version="1.13.0" />
        <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.4" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    </ItemGroup>
</Project>
